containers:
  jenkins:
    image: georvic/cd4ml-build-master:2
  jupyter:
    image: jupyter/minimal-notebook:54462805efcb
  minio:
    image: minio/minio:RELEASE.2020-08-08T04-50-06Z
  mlflow:
    image: georvic/cd4ml-mlflow:1
  models:
    image: georvic/cd4ml-model-server:1
  welcome:
    image: georvic/cd4ml-welcome:1
  fluentd:
    image: georvic/cd4ml-fluentd:1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0

volumes:
  local: true
  minio:
    local:
      path: ~
    capacity: 10Gi
