apiVersion: v1
data:
  MINIO_ACCESS_KEY: {{ .Values.secrets.minio.access_key | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minio.secret_key | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-secret
type: Opaque
