apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: minio-storage
  name: minio-storage
spec:
  {{- if and .Values.volumes.local }}
  storageClassName: hostpath
  {{- end }}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
