apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: es01
  name: es01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es01
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/jenkins-nw: "true"
        io.kompose.service: es01
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.name
              value: es-docker-cluster
            - name: discovery.type
              value: single-node
            - name: http.host
              value: 0.0.0.0
            - name: http.port
              value: "9200"
            - name: node.name
              value: es01
          image: {{ .Values.containers.elastic.image }}
          livenessProbe:
            exec:
              command:
                - curl -s http://localhost:9200 >/dev/null; if [[ $? == 52 ]]; then echo 0; else echo 1; fi
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: es01
          ports:
            - containerPort: 9200
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data01
      restartPolicy: Always
      volumes:
        - name: data01
          persistentVolumeClaim:
            claimName: data01
status: {}
