apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dev
  name: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dev
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/jenkins-nw: "true"
        io.kompose.service: dev
    spec:
      containers:
        - args:
            - jupyter
            - lab
            - --LabApp.token=
          command:
            - start.sh
          env:
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
          image: {{ .Values.containers.jupyter.image }}
          name: dev
          ports:
            - containerPort: 8888
          resources: {}
          volumeMounts:
            - mountPath: /home/jovyan/
              name: dev-claim0
      restartPolicy: Always
      volumes:
        - name: dev-claim0
          persistentVolumeClaim:
            claimName: dev-claim0
status: {}
