apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: model
  name: model
spec:
  ports:
    - name: "11000"
      port: 11000
      targetPort: 5005
  selector:
    io.kompose.service: model
status:
  loadBalancer: {}
