apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: model
  name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: model
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/jenkins_nw: "true"
        io.kompose.service: model
    spec:
      containers:
        - env:
            - name: ACCESS_KEY
            - name: FLUENTD_HOST
              value: fluentd
            - name: FLUENTD_PORT
              value: "24224"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: SECRET_KEY
          image: model
          name: model
          ports:
            - containerPort: 5005
          resources: {}
      restartPolicy: Always
status: {}
