apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: welcome
  name: welcome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: welcome
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/jenkins_nw: "true"
        io.kompose.service: welcome
    spec:
      containers:
        - image: httpd:2.4-alpine
          name: welcome-server
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs/
              name: welcome-claim0
      restartPolicy: Always
      volumes:
        - name: welcome-claim0
          persistentVolumeClaim:
            claimName: welcome-claim0
status: {}
