apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mlflow
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlflow
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/jenkins-nw: "true"
        io.kompose.service: mlflow
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_SECRET_KEY
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
          image: {{ .Values.containers.mlflow.image }}
          name: mlflow
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /mnt/mlflow
              name: mlflow-storage
      restartPolicy: Always
      volumes:
        - name: mlflow-storage
          persistentVolumeClaim:
            claimName: mlflow-storage
status: {}
