
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: mlflow-storage
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.volumes.mlflow.capacity }}
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: {{ .Values.volumes.mlflow.local.path }}
    type: ""
  {{- if and .Values.volumes.local }}
  storageClassName: hostpath
  {{- end }}
