apiVersion: v1
data:
  jenkins-admin-password: {{ .Values.secrets.jenkins.jenkins_admin_password | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-admin-password
  name: jenkins-admin-password
type: Opaque
