apiVersion: v1
data:
  jenkins-admin-password: bXk1M2N1cjNwNDU1dy5yZA==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-admin-password
  name: jenkins-admin-password
type: Opaque
